"""Build deployable fixture projects for the E2E deploy matrix.

Each matrix row becomes a standalone project directory under ``build/``:

    build/e2e-01/
      service.py            entrypoint registering the row's endpoints
      services/             copy of APIPod/test/services (shared modules)
      files/                copy of APIPod/test/files (media fixtures)
      requirements.txt
      apipod-deploy/
        apipod.json
        Dockerfile

The layout mirrors what a real user project looks like, so ``apipod deploy``
runs unmodified against it.
"""
from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import List

E2E_DIR = Path(__file__).resolve().parent
TEST_DIR = E2E_DIR.parent
BUILD_DIR = E2E_DIR / "build"

_SERVICE_TEMPLATE = '''"""E2E fixture entrypoint (generated by e2e_deploy/fixtures.py)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from apipod import APIPod

{imports}

app = APIPod()
{registrations}
'''

_LAUNCH_ALL_TEMPLATE = '''"""E2E fixture entrypoint: all service groups (generated)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from apipod import APIPod
from services import core_service, schema_service, streaming_service

app = APIPod(title="APIPod test services (all)")

core = APIPod()
core_service.register(core)
app.include_router(core, prefix="/core")

schemas = APIPod()
schema_service.register_all(schemas)
schema_service.register_extended(schemas)
schema_service.register_mapping(schemas)
app.include_router(schemas, prefix="/schemas")

streaming = APIPod()
streaming_service.register(streaming)
app.include_router(streaming, prefix="/streaming")
'''

_DOCKERFILE = '''# Generated E2E deploy image (CPU-only test services).
FROM python:3.11-slim

RUN apt-get update && apt-get install -y ffmpeg && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt "runpod>=1.7.7"

COPY . .

ENV APIPOD_COMPUTE="serverless"
ENV APIPOD_PROVIDER="runpod"
ENV APIPOD_HOST="0.0.0.0"
ENV APIPOD_PORT=8000

EXPOSE 8000

CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8000"]
'''

_APIPOD_JSON = '''{{
    "entrypoint": "service.py",
    "title": "{title}",
    "python_version": "3.11",
    "pytorch": null,
    "tensorflow": null,
    "onnx": null,
    "models": [],
    "includes": []
}}
'''


@dataclass
class MatrixRow:
    row_id: str
    title: str
    imports: str
    registrations: str
    fastsdk_subset: str  # pytest -k expression against fastSDK's debug-services suite
    launch_all: bool = False
    needs_files: bool = False
    extra_requirements: List[str] = field(default_factory=list)


MATRIX: List[MatrixRow] = [
    MatrixRow(
        row_id="e2e-01",
        title="e2e-01-core-minimal",
        imports="from services import core_service",
        registrations="core_service.register_minimal(app)",
        fastsdk_subset="test_iterate_all_endpoints",
    ),
    MatrixRow(
        row_id="e2e-02",
        title="e2e-02-schema-all",
        imports="from services import schema_service",
        registrations="schema_service.register_all(app)",
        fastsdk_subset="chat_raw or embedding_raw",
        needs_files=True,
    ),
    MatrixRow(
        row_id="e2e-03",
        title="e2e-03-schema-extended",
        imports="from services import schema_service",
        registrations="schema_service.register_extended(app)",
        fastsdk_subset="test_connect_chat_extended",
        needs_files=True,
    ),
    MatrixRow(
        row_id="e2e-04",
        title="e2e-04-streaming",
        imports="from services import streaming_service",
        registrations="streaming_service.register(app)",
        fastsdk_subset="test_streaming_text or test_streaming_chat_schema",
    ),
    MatrixRow(
        row_id="e2e-05",
        title="e2e-05-all-groups",
        imports="",
        registrations="",
        fastsdk_subset="",  # empty -k: run the full suite
        launch_all=True,
        needs_files=True,
    ),
]


def build_fixture(row: MatrixRow, clean: bool = True) -> Path:
    """Materialize one matrix row as a deployable project directory."""
    target = BUILD_DIR / row.row_id
    if clean and target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)

    shutil.copytree(TEST_DIR / "services", target / "services", dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns("__pycache__"))
    if row.needs_files:
        shutil.copytree(TEST_DIR / "files", target / "files", dirs_exist_ok=True)

    if row.launch_all:
        service_code = _LAUNCH_ALL_TEMPLATE
    else:
        service_code = _SERVICE_TEMPLATE.format(imports=row.imports, registrations=row.registrations)
    (target / "service.py").write_text(service_code, encoding="utf-8")

    requirements = ["apipod", *row.extra_requirements]
    (target / "requirements.txt").write_text("\n".join(requirements) + "\n", encoding="utf-8")

    deploy_dir = target / "apipod-deploy"
    deploy_dir.mkdir(exist_ok=True)
    (deploy_dir / "apipod.json").write_text(_APIPOD_JSON.format(title=row.title), encoding="utf-8")
    (deploy_dir / "Dockerfile").write_text(_DOCKERFILE, encoding="utf-8")
    return target


def build_all() -> List[Path]:
    return [build_fixture(row) for row in MATRIX]


if __name__ == "__main__":
    for path in build_all():
        print(f"built {path}")
